#!/usr/bin/env python3
"""Sub-MP-D3 Task A0: Offline Qwen3 prompt token encoding.

Encodes the Stage 11 Soft-Closure prompt prefix using Qwen3 tokenizer.
Output: Rust const array for inference.rs PROMPT_TOKENS.

Design decision (Option B): no manual hardcoding, no speculation, only
authoritative tokenizer encoding.

Ensures Sub-MP-C3 anchor preservation — first token MUST be 9707
("Hello"), else encoding-mismatch detected and the build halts.
"""
import sys
from pathlib import Path

PROMPT = "Hello World I'm the first LLM running on Bare-Metal"

# Sub-MP-C3 ground truth anchor expectation
EXPECTED_FIRST_TOKEN = 9707  # "Hello" per Sub-MP-C3


def encode_via_tokenizer_json(tokenizer_path):
    """Encode using tokenizer.json (HuggingFace Tokenizers format)."""
    try:
        from tokenizers import Tokenizer
    except ImportError:
        print("ERROR: 'tokenizers' library not available", file=sys.stderr)
        print("Install via: pip3 install tokenizers", file=sys.stderr)
        sys.exit(1)

    tokenizer = Tokenizer.from_file(str(tokenizer_path))
    encoding = tokenizer.encode(PROMPT)
    return encoding.ids, tokenizer


def main():
    if len(sys.argv) < 2:
        print("Usage: encode_prompt.py <path-to-tokenizer.json>", file=sys.stderr)
        sys.exit(1)

    tokenizer_path = Path(sys.argv[1])
    if not tokenizer_path.exists():
        print("ERROR: Tokenizer not found at {}".format(tokenizer_path),
              file=sys.stderr)
        sys.exit(1)

    token_ids, tokenizer = encode_via_tokenizer_json(tokenizer_path)

    # CRITICAL: Sub-MP-C3 anchor verification per beta-anchor strategy
    if token_ids[0] != EXPECTED_FIRST_TOKEN:
        print("FATAL: First token = {}, expected {} (Sub-MP-C3 ground truth)".format(
            token_ids[0], EXPECTED_FIRST_TOKEN), file=sys.stderr)
        print("Tokenizer drift detected — halt and report required", file=sys.stderr)
        sys.exit(2)

    n = len(token_ids)
    print("// Auto-generated by tools/encode_prompt.py — DO NOT EDIT MANUALLY")
    print("// Source prompt: {!r}".format(PROMPT))
    print("// Tokenizer: {}".format(tokenizer_path))
    print("// Encoded: {} tokens".format(n))
    print("// Sub-MP-C3 anchor verified: tokens[0] = {} (Token-ID 9707 'Hello')".format(
        token_ids[0]))
    print("")

    # Emit human-readable mapping for verification
    print("// Verification table (token-ID -> decoded string fragment):")
    for i, tid in enumerate(token_ids):
        decoded = tokenizer.decode([tid])
        print("//   [{:>2}] {:>6} -> {!r}".format(i, tid, decoded))
    print("")

    print("/// Stage 11 Soft-Closure prompt prefix, encoded via Qwen3 tokenizer.")
    print("/// Per Sub-MP-D3 C3 ratification (Option gamma Hybrid):")
    print("///   full prompt + AI continuation.")
    print("/// Per beta-anchor strategy: tokens[0] = 9707 preserves Sub-MP-C3")
    print("///   ground truth chain.")
    print("pub const PROMPT_TOKENS: [u32; {}] = [".format(n))
    for i, tid in enumerate(token_ids):
        decoded = tokenizer.decode([tid])
        anchor_note = "  <- beta-anchor" if i == 0 else ""
        print("    {:>6},  // token[{:>2}] {!r}{}".format(tid, i, decoded, anchor_note))
    print("];")
    print("")
    print("/// Number of prompt tokens (compile-time constant).")
    print("pub const PROMPT_TOKEN_COUNT: usize = {};".format(n))


if __name__ == "__main__":
    main()
