// SPDX-License-Identifier: AGPL-3.0-or-later
//! AOT-compiled program execution path (Stage 10 MP4).
//!
//! # Architecture
//!
//! Stage 10 introduces Ahead-Of-Time compilation as the primary
//! execution path for Quarks code. The AOT compiler
//! ([`quarks-codegen`]) translates S-Expression IR to native x86_64
//! machine code at kernel build time (see `build.rs`). The resulting
//! `program.bin` is embedded into the kernel binary via `include_bytes!`
//! and executed at boot via this module.
//!
//! Per V3 (`docs/ARCHITECTURE.md` Z.273-274): "Stage 10 introduces the
//! AOT compiler and the interpreter becomes a fallback / debugging
//! tool." Both paths run in MP4 to verify semantic equivalence
//! (interpreter: `Integer(3)`; AOT: raw `3`).
//!
//! # Memory model
//!
//! AOT-compiled bytes are copied into the KERNEL_ARENA bump-pointer
//! arena and executed in-place. This is V3-architecturally correct:
//!
//! Per V3 (Z.36-39 and Z.43-46): "Safety is enforced by the Validator
//! and the type system, not by hardware boundaries." "Memory protection
//! is shifted from hardware page tables to the type system and the
//! capability registry."
//!
//! AOT-compiled code has passed the validator pipeline (parse →
//! type_check → codegen) at build time. It contains only
//! validator-approved operations. Hardware-level W^X isolation is
//! architecturally redundant for Zero-native trusted code per V3
//! Z.221-224.

use core::fmt::Write;
use core::mem;

use crate::arch::serial;
use crate::memory;

/// Embedded AOT-compiled boot program.
///
/// Generated by `kernel/build.rs` (MP3 pipeline):
/// `boot.ir` → validator → codegen → x86_64 machine code → `program.bin`.
/// Bytes are deterministic per ADR-026.
const BOOT_PROGRAM: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/program.bin"));

/// Errors during AOT boot-program execution.
#[derive(Debug)]
pub enum AotError {
    ArenaUnavailable,
    ArenaAllocFailed,
}

/// Execute the embedded AOT program.
///
/// 1. Copy `BOOT_PROGRAM` into KERNEL_ARENA (writable + executable)
/// 2. Cast arena pointer to `extern "C" fn() -> i64`
/// 3. Call and return the result
///
/// # Safety
///
/// This function transmutes a data pointer to a function pointer and
/// invokes it. The safety invariants are:
///
/// - `BOOT_PROGRAM` was generated by the V3-validated AOT pipeline and
///   contains only validator-approved x86_64 instructions.
/// - The KERNEL_ARENA pages are mapped `PRESENT | WRITABLE`, and NX is
///   never set in the kernel page tables (verified in MP4 Pre-Discovery).
/// - The byte sequence ends in `ret` (verified by codegen unit tests).
/// - System V AMD64 calling convention is satisfied: no arguments in,
///   `i64` return in RAX (matched by the `extern "C" fn() -> i64` cast).
unsafe fn execute() -> Result<i64, AotError> {
    // Acquire KERNEL_ARENA and copy AOT bytes into it
    let code_ptr = {
        let mut arena_guard = memory::KERNEL_ARENA.lock();
        let arena = arena_guard.as_mut().ok_or(AotError::ArenaUnavailable)?;

        let code_slice = arena
            .alloc_slice_copy(BOOT_PROGRAM)
            .map_err(|_| AotError::ArenaAllocFailed)?;

        code_slice.as_ptr()
        // arena_guard dropped here — lock released before execution
    };

    // Cast data pointer to function pointer per System V AMD64 ABI
    let f: extern "C" fn() -> i64 = mem::transmute(code_ptr);

    // Execute. RSP is 16-byte aligned by Rust ABI; AOT prologue
    // (push rbp; mov rbp, rsp) maintains the invariant.
    let result = f();

    Ok(result)
}

/// Run AOT path and report result via serial.
///
/// High-level boot-time entry point called from `kernel_main` after
/// the interpreter path completes. Both paths run in MP4 to verify
/// semantic equivalence.
pub fn run_and_report() {
    let _ = writeln!(serial::Serial, "Stage 10: starting AOT execution path...");
    let _ = writeln!(
        serial::Serial,
        "Stage 10: AOT program is {} bytes (from kernel build)",
        BOOT_PROGRAM.len()
    );

    // SAFETY: see `execute` doc-comment.
    let result = unsafe { execute() };

    match result {
        Ok(value) => {
            let _ = writeln!(serial::Serial, "Stage 10: AOT execution result: {}", value);
            let _ = writeln!(
                serial::Serial,
                "Stage 10: V3 Phase 3 AOT path verified \
                 — bare-metal execution of Quarks via native x86_64 code"
            );
        }
        Err(e) => {
            let _ = writeln!(serial::Serial, "Stage 10: AOT execution FAILED: {:?}", e);
        }
    }
}

// === Stage 10 MP6: Performance Regression Suite ===

use crate::arch::cycles;

/// Run the AOT path `BENCH_ITERATIONS` times and return total cycles.
///
/// Per Stage 10 MP6 / ADR-026 MP6 mandate. The AOT-compiled program is
/// allocated once into KERNEL_ARENA and then invoked in a tight loop.
/// This measures pure execution overhead, not allocation overhead.
///
/// # Safety
///
/// See `execute()` doc-comment. The same safety invariants apply across
/// the loop: BOOT_PROGRAM is validator-approved, KERNEL_ARENA is
/// PRESENT|WRITABLE|non-NX, and the function pointer cast matches the
/// codegen entry-wrapper signature.
unsafe fn execute_loop() -> Result<u64, AotError> {
    // Allocate once outside the loop — measures execution, not allocation.
    let code_ptr = {
        let mut arena_guard = memory::KERNEL_ARENA.lock();
        let arena = arena_guard.as_mut().ok_or(AotError::ArenaUnavailable)?;
        let code_slice = arena
            .alloc_slice_copy(BOOT_PROGRAM)
            .map_err(|_| AotError::ArenaAllocFailed)?;
        code_slice.as_ptr()
    };

    let f: extern "C" fn() -> i64 = mem::transmute(code_ptr);

    let start = cycles::rdtsc_serialized();
    let mut acc: i64 = 0;
    for _ in 0..cycles::BENCH_ITERATIONS {
        // core::hint::black_box to prevent compiler from constant-folding
        // the loop body away.
        acc = acc.wrapping_add(core::hint::black_box(f()));
    }
    let end = cycles::rdtsc_serialized();

    // Use the accumulator to keep the loop alive.
    let _ = core::hint::black_box(acc);

    Ok(end.wrapping_sub(start))
}

/// Run AOT loop bench and report cycles via serial.
pub fn run_bench() -> Option<u64> {
    let _ = writeln!(
        serial::Serial,
        "Stage 10 MP6: AOT loop bench ({} iterations)...",
        cycles::BENCH_ITERATIONS
    );
    // SAFETY: see execute_loop doc-comment.
    let result = unsafe { execute_loop() };
    match result {
        Ok(total_cycles) => {
            let per_iter = total_cycles / cycles::BENCH_ITERATIONS;
            let _ = writeln!(
                serial::Serial,
                "Stage 10 MP6: AOT total = {} cycles, ~{} cycles/iter",
                total_cycles,
                per_iter
            );
            Some(total_cycles)
        }
        Err(e) => {
            let _ = writeln!(serial::Serial, "Stage 10 MP6: AOT bench FAILED: {:?}", e);
            None
        }
    }
}
