// SPDX-License-Identifier: AGPL-3.0-or-later
//! Sub-MP-D4: BPE Detokenizer for the kernel's embedded vocabulary.
//!
//! Converts Token-ID sequences from autoregressive generation into
//! human-readable UTF-8 bytes. Static vocabulary data embedded at
//! compile-time via `include_bytes!()` per V3.1 Pillar 1 (zero runtime
//! IO) + Pillar 7 (canonical shared data, no platform branching).
//!
//! Per V3.1 Pillar 8 (Z.276-282): Rust detokenizer is temporary; will
//! migrate to Quarks in Stage 12+ when Validator + interpreter
//! mature.
//!
//! Design decision (V3.1 strict trajectory): NO platform-specific
//! optimization. Scalar O(1) lookup only.
//!
//! # Vocabulary dispatch
//!
//! The vocab is selected at build time via the `kimi-k26-vocab` Cargo
//! feature:
//!
//! * **default**: Qwen3 vocabulary (151 669 tokens), generated by
//!   `tools/extract_vocab.py` from Qwen3-1.7B's `tokenizer.json`.
//!   This is the β-anchor-bearing path — do not modify.
//! * **`kimi-k26-vocab`**: Kimi K2.6 / Llama-3 family vocabulary
//!   (128 256 tokens). The vocab binaries
//!   (`kimi_vocab_bytes.bin` / `kimi_vocab_offsets.bin`) are
//!   placeholder stubs in this repo — run `tools/extract_vocab.py`
//!   against the Kimi `tokenizer.json` to regenerate. Until then,
//!   `decode_token` returns an empty slice for every token (the
//!   generation loop falls through to printing the raw token id on
//!   serial; the boot doesn't crash).

// ── Vocab dispatch ──────────────────────────────────────────────────

#[cfg(not(feature = "kimi-k26-vocab"))]
mod vocab {
    /// Qwen3 vocabulary size (per offline extraction via
    /// `tools/extract_vocab.py`).
    pub const DETOK_VOCAB_SIZE: usize = 151_669;

    /// Concatenated UTF-8 byte sequences for all Qwen3 vocabulary tokens.
    /// Generated by `tools/extract_vocab.py` from `tokenizer.json`.
    pub static VOCAB_BYTES: &[u8] = include_bytes!("vocab_bytes.bin");

    /// Byte offset table (u32 LE): `DETOK_VOCAB_SIZE + 1` entries.
    /// Entry i gives the start offset of Token-ID i in `VOCAB_BYTES`.
    /// Entry `DETOK_VOCAB_SIZE` gives the end offset (= `VOCAB_BYTES.len()`).
    pub static VOCAB_OFFSETS_RAW: &[u8] = include_bytes!("vocab_offsets.bin");
}

#[cfg(feature = "kimi-k26-vocab")]
mod vocab {
    /// Kimi K2.6 vocabulary size — upper bound, not a binding limit.
    /// Source of truth at runtime is `tokenizer.ggml.tokens` in the
    /// GGUF (installed via [`install_runtime_vocab`]); this constant
    /// only gates the compile-time fallback lookup when the runtime
    /// vocab install failed. Sized at 200 000 — a safe maximum that
    /// clears Kimi K2.6 (~163 840), every DeepSeek-V2/V3 tokenizer
    /// shipped to date, and leaves headroom for ASCII-extended
    /// variants the operator may load post-boot. SPEC: any Kimi
    /// /Llama-3 family token id must satisfy `tid < DETOK_VOCAB_SIZE`
    /// or `decode_token` silently returns an empty slice and the
    /// generation loop prints raw token ids (the bug this fix closes).
    /// Per-call bounds check (`need = (tid + 2) * 4` against
    /// `VOCAB_OFFSETS_RAW.len()`) keeps stub-vocab builds safe.
    pub const DETOK_VOCAB_SIZE: usize = 200_000;

    /// Concatenated UTF-8 byte sequences for all Kimi vocabulary tokens.
    /// TODO: regenerate from Kimi `tokenizer.json` via
    ///       `tools/extract_vocab.py`. Until then, this is a stub.
    pub static VOCAB_BYTES: &[u8] = include_bytes!("kimi_vocab_bytes.bin");

    /// Byte offset table (u32 LE) for the Kimi vocab. Stub today.
    pub static VOCAB_OFFSETS_RAW: &[u8] = include_bytes!("kimi_vocab_offsets.bin");
}

pub use vocab::DETOK_VOCAB_SIZE;

/// Read u32 little-endian from byte slice at given byte offset.
/// Per V3.1 Pillar 7: explicit LE decoding, no platform endianness assumptions.
#[inline]
fn read_u32_le(bytes: &[u8], offset: usize) -> u32 {
    let b0 = bytes[offset] as u32;
    let b1 = bytes[offset + 1] as u32;
    let b2 = bytes[offset + 2] as u32;
    let b3 = bytes[offset + 3] as u32;
    b0 | (b1 << 8) | (b2 << 16) | (b3 << 24)
}

/// Get UTF-8 byte slice for given Token-ID. O(1) lookup via offset table.
///
/// Consult order:
///   1. Runtime vocab installed via [`install_runtime_vocab`] (if any).
///      Populated at boot from `TensorIndex.tokenizer.tokens` when the
///      GGUF carries `tokenizer.ggml.tokens`. This is the path Kimi K2.6
///      / any non-Qwen3 model uses.
///   2. Compile-time vocab (Qwen3 default, or the Kimi-stub placeholder
///      under the `kimi-k26-vocab` feature). This is the β-anchor
///      bearing path — verbatim Qwen3 bytes.
///
/// Returns empty slice if:
///   * `token_id` is out of range in every consulted vocab
///   * the embedded offset table is too small (placeholder stub build)
///
/// The kernel's generation loop tolerates an empty decode by printing
/// the token id on serial instead of rendered text.
///
/// Per V3.1 Pillar 7: same algorithm both platforms (no platform branching).
#[inline]
pub fn decode_token(token_id: u32) -> &'static [u8] {
    // Runtime vocab takes priority when available. Use a lock-free
    // load of the `RUNTIME_VOCAB` pointer to keep the hot path free
    // of mutex contention (the slot is written once at boot, read
    // many times per generation step).
    if let Some(bytes) = runtime_decode(token_id) {
        return bytes;
    }

    let tid = token_id as usize;
    if tid >= DETOK_VOCAB_SIZE {
        return &[];
    }
    let need = (tid + 2) * 4;
    if vocab::VOCAB_OFFSETS_RAW.len() < need {
        return &[];
    }
    let start = read_u32_le(vocab::VOCAB_OFFSETS_RAW, tid * 4) as usize;
    let end = read_u32_le(vocab::VOCAB_OFFSETS_RAW, (tid + 1) * 4) as usize;
    if end > vocab::VOCAB_BYTES.len() || start > end {
        return &[];
    }
    &vocab::VOCAB_BYTES[start..end]
}

// ── Runtime vocab (installed at boot from GGUF) ─────────────────────

use core::sync::atomic::{AtomicPtr, AtomicUsize, Ordering};

/// Runtime vocabulary built from `tokenizer.ggml.tokens` in the loaded
/// GGUF. The kernel allocates the storage from `KERNEL_ARENA`, then
/// stores raw pointers + length here; subsequent `decode_token` calls
/// read the vocab without acquiring a lock.
struct RuntimeVocab {
    tokens_bytes_ptr: *const u8,
    tokens_bytes_len: usize,
    offsets_ptr: *const u32,
    /// `vocab_size` — `offsets_ptr` points to `vocab_size + 1` entries
    /// (the final entry is the end offset, matching the compile-time
    /// vocab convention).
    vocab_size: usize,
}

// SAFETY: the runtime vocab is written exactly once during boot via
// `install_runtime_vocab` while no other CPU is running (APs aren't
// woken yet). Subsequent access is read-only and the underlying arena
// allocation lives for the kernel's lifetime, so the raw pointers are
// stable.
unsafe impl Sync for RuntimeVocab {}

static RUNTIME_TOKENS_PTR: AtomicPtr<u8> = AtomicPtr::new(core::ptr::null_mut());
static RUNTIME_TOKENS_LEN: AtomicUsize = AtomicUsize::new(0);
static RUNTIME_OFFSETS_PTR: AtomicPtr<u32> = AtomicPtr::new(core::ptr::null_mut());
static RUNTIME_VOCAB_SIZE: AtomicUsize = AtomicUsize::new(0);

#[inline]
fn runtime_decode(token_id: u32) -> Option<&'static [u8]> {
    let vocab_size = RUNTIME_VOCAB_SIZE.load(Ordering::Acquire);
    if vocab_size == 0 {
        return None;
    }
    let tid = token_id as usize;
    if tid >= vocab_size {
        return Some(&[]);
    }
    let offsets_ptr = RUNTIME_OFFSETS_PTR.load(Ordering::Acquire);
    if offsets_ptr.is_null() {
        return None;
    }
    // SAFETY: `offsets_ptr` was set once at boot to an arena slice of
    // `vocab_size + 1` u32 entries; `tid + 1 <= vocab_size` so the
    // indexed reads stay in bounds.
    let (start, end) = unsafe {
        let off0 = *offsets_ptr.add(tid);
        let off1 = *offsets_ptr.add(tid + 1);
        (off0 as usize, off1 as usize)
    };
    let tokens_ptr = RUNTIME_TOKENS_PTR.load(Ordering::Acquire);
    let tokens_len = RUNTIME_TOKENS_LEN.load(Ordering::Acquire);
    if tokens_ptr.is_null() || end > tokens_len || start > end {
        return None;
    }
    // SAFETY: arena slice lives forever; bounds verified above.
    let slice = unsafe { core::slice::from_raw_parts(tokens_ptr.add(start), end - start) };
    Some(slice)
}

/// Install a runtime vocabulary built from GGUF `tokenizer.ggml.tokens`.
///
/// Must be called exactly once during boot before any user-visible
/// token decoding (the kernel's deepseek2 generation loop calls this
/// immediately after parsing the GGUF). Subsequent calls overwrite
/// the previously-installed vocab — caller's responsibility to ensure
/// only one is active.
///
/// Returns `Err` if the arena couldn't satisfy the allocation; in that
/// case the runtime vocab stays uninstalled and `decode_token` falls
/// through to the compile-time path.
pub fn install_runtime_vocab(tokenizer: &zero_gguf_parser::TokenizerData) -> Result<(), ()> {
    use quarks_arena::ArenaError;
    use core::fmt::Write;

    let serial = &mut crate::arch::serial::Serial;
    let vocab_size = tokenizer.len();
    if vocab_size == 0 || tokenizer.offsets.len() != vocab_size + 1 {
        return Err(());
    }

    // The tokenizer ships flat byte + offset buffers — copy them into
    // the kernel arena in TWO bulk allocations (no per-token churn).
    let mut guard = crate::memory::KERNEL_ARENA.lock();
    let arena = guard.as_mut().ok_or(())?;

    let bytes_dst: &'static mut [u8] = unsafe {
        let s = arena
            .alloc_slice_copy::<u8>(&tokenizer.bytes)
            .map_err(|e: ArenaError| {
                let _ = writeln!(serial, "[detok] runtime vocab byte alloc failed: {:?}", e);
            })?;
        core::mem::transmute::<&mut [u8], &'static mut [u8]>(s)
    };

    let offsets_dst: &'static mut [u32] = unsafe {
        let s = arena
            .alloc_slice_copy::<u32>(&tokenizer.offsets)
            .map_err(|e: ArenaError| {
                let _ = writeln!(serial, "[detok] runtime vocab offset alloc failed: {:?}", e);
            })?;
        core::mem::transmute::<&mut [u32], &'static mut [u32]>(s)
    };

    // Publish in order so a concurrent reader (none in practice
    // pre-AP-wake, but defensive) sees a consistent view.
    RUNTIME_TOKENS_PTR.store(bytes_dst.as_mut_ptr(), Ordering::Release);
    RUNTIME_TOKENS_LEN.store(bytes_dst.len(), Ordering::Release);
    RUNTIME_OFFSETS_PTR.store(offsets_dst.as_mut_ptr(), Ordering::Release);
    RUNTIME_VOCAB_SIZE.store(vocab_size, Ordering::Release);

    let _ = writeln!(
        serial,
        "[detok] runtime vocab installed: {} tokens, {} byte payload",
        vocab_size,
        tokenizer.bytes.len()
    );
    Ok(())
}

/// `true` if a runtime vocab is currently installed.
pub fn has_runtime_vocab() -> bool {
    RUNTIME_VOCAB_SIZE.load(Ordering::Acquire) > 0
}

/// Effective vocabulary size for the currently-active decoder path.
///
/// Returns the runtime vocab size when a GGUF-derived vocab is installed,
/// otherwise the compile-time `DETOK_VOCAB_SIZE`. Diagnostic prints
/// should use this rather than `DETOK_VOCAB_SIZE` so the operator sees
/// the size the decoder actually services.
#[inline]
pub fn effective_vocab_size() -> usize {
    let runtime = RUNTIME_VOCAB_SIZE.load(Ordering::Acquire);
    if runtime > 0 {
        runtime
    } else {
        DETOK_VOCAB_SIZE
    }
}
