// SPDX-License-Identifier: AGPL-3.0-or-later
use quarks_frontend::lexer::{tokenize, LexError, LexErrorKind, Span};
use quarks_frontend::parser::{parse, ParseError, ParseErrorKind};
use quarks_frontend::type_checker::{check, TypeError, TypeErrorKind};

/// A diagnostic produced by DiagnosticsEngine — uniform wrapper over
/// lex errors, parse errors, and type-check errors from the source-
/// language frontend.
///
/// MP5 swap note: the LSP pipeline is now source-language only.
/// S-expression IR is generated by the Codegen step (frontend::codegen)
/// but is not user-facing; the LSP never sees it.
#[derive(Debug, Clone)]
pub struct EngineDiagnostic {
    pub kind: EngineDiagnosticKind,
    pub span: ByteSpan,
    pub message: String,
    /// Full JSON serialization of the underlying error.
    /// Exposed to LSP clients via `Diagnostic.data` for structured
    /// LLM consumption.
    pub error_json: String,
}

/// Diagnostic kind — discriminates lex-time, parse-time, and
/// type-check-time errors.
#[derive(Debug, Clone)]
pub enum EngineDiagnosticKind {
    LexError(LexErrorKind),
    ParseError(ParseErrorKind),
    TypeCheckError(TypeErrorKind),
}

/// Byte-offset span in the original source. Direct from frontend
/// lexer/parser/type-checker output — no path mapping needed.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ByteSpan {
    pub start: usize,
    pub end: usize,
}

impl From<Span> for ByteSpan {
    fn from(s: Span) -> Self {
        Self {
            start: s.start,
            end: s.end,
        }
    }
}

/// Stateless diagnostic producer.
///
/// `diagnose` accepts raw `.qk` source text and returns a list of
/// `EngineDiagnostic`. The returned list is empty if the source is
/// valid. The list has at most one element (Fail-Fast semantics).
pub struct DiagnosticsEngine;

impl DiagnosticsEngine {
    pub fn new() -> Self {
        Self
    }

    /// Run the full source pipeline: tokenize → parse → type-check.
    /// Fail-Fast: returns at most one diagnostic.
    pub fn diagnose(&self, source: &str) -> Vec<EngineDiagnostic> {
        match tokenize(source) {
            Err(e) => vec![lex_error_to_diagnostic(e)],
            Ok(tokens) => match parse(&tokens) {
                Err(e) => vec![parse_error_to_diagnostic(e)],
                Ok(program) => match check(&program) {
                    Err(e) => vec![type_check_error_to_diagnostic(e)],
                    Ok(_) => Vec::new(),
                },
            },
        }
    }
}

impl Default for DiagnosticsEngine {
    fn default() -> Self {
        Self::new()
    }
}

fn lex_error_to_diagnostic(err: LexError) -> EngineDiagnostic {
    let message = err.message.clone();
    let span = ByteSpan::from(err.span);
    let kind_str = lex_error_kind_str(&err.kind);
    let error_json = format!(
        r#"{{"error":{{"kind":"{}","message":"{}","span":{{"start":{},"end":{}}}}}}}"#,
        kind_str,
        json_escape(&message),
        span.start,
        span.end
    );
    EngineDiagnostic {
        kind: EngineDiagnosticKind::LexError(err.kind),
        span,
        message,
        error_json,
    }
}

fn parse_error_to_diagnostic(err: ParseError) -> EngineDiagnostic {
    let message = err.message.clone();
    let span = ByteSpan::from(err.span);
    let kind_str = parse_error_kind_str(&err.kind);
    let error_json = format!(
        r#"{{"error":{{"kind":"{}","message":"{}","span":{{"start":{},"end":{}}}}}}}"#,
        kind_str,
        json_escape(&message),
        span.start,
        span.end
    );
    EngineDiagnostic {
        kind: EngineDiagnosticKind::ParseError(err.kind),
        span,
        message,
        error_json,
    }
}

fn type_check_error_to_diagnostic(err: TypeError) -> EngineDiagnostic {
    let message = err.message.clone();
    let span = ByteSpan::from(err.span);
    let kind_str = type_error_kind_str(&err.kind);
    let error_json = format!(
        r#"{{"error":{{"kind":"{}","message":"{}","span":{{"start":{},"end":{}}}}}}}"#,
        kind_str,
        json_escape(&message),
        span.start,
        span.end
    );
    EngineDiagnostic {
        kind: EngineDiagnosticKind::TypeCheckError(err.kind),
        span,
        message,
        error_json,
    }
}

fn lex_error_kind_str(kind: &LexErrorKind) -> &'static str {
    match kind {
        LexErrorKind::UnexpectedChar(_) => "UnexpectedChar",
        LexErrorKind::UnterminatedBlockComment => "UnterminatedBlockComment",
        LexErrorKind::InvalidInteger => "InvalidInteger",
        LexErrorKind::IntegerOverflow => "IntegerOverflow",
        LexErrorKind::InvalidBytes => "InvalidBytes",
        LexErrorKind::InvalidHandle => "InvalidHandle",
        LexErrorKind::InvalidOperator => "InvalidOperator",
    }
}

fn parse_error_kind_str(kind: &ParseErrorKind) -> &'static str {
    match kind {
        ParseErrorKind::UnexpectedToken { .. } => "UnexpectedToken",
        ParseErrorKind::UnexpectedEof => "UnexpectedEof",
        ParseErrorKind::InvalidType => "InvalidType",
        ParseErrorKind::ExpectedExpression => "ExpectedExpression",
        ParseErrorKind::ExpectedIdentifier => "ExpectedIdentifier",
        ParseErrorKind::EmptyProgram => "EmptyProgram",
    }
}

fn type_error_kind_str(kind: &TypeErrorKind) -> &'static str {
    match kind {
        TypeErrorKind::TypeMismatch { .. } => "TypeMismatch",
        TypeErrorKind::UndefinedIdentifier { .. } => "UndefinedIdentifier",
        TypeErrorKind::UndefinedFunction { .. } => "UndefinedFunction",
        TypeErrorKind::ArityMismatch { .. } => "ArityMismatch",
        TypeErrorKind::DuplicateFunction { .. } => "DuplicateFunction",
        TypeErrorKind::BreakOutsideLoop => "BreakOutsideLoop",
        TypeErrorKind::MissingReturn { .. } => "MissingReturn",
        TypeErrorKind::InvalidIntentCall => "InvalidIntentCall",
    }
}

/// Minimal JSON string escape for error messages.
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn valid_source_produces_empty_diagnostics() {
        let engine = DiagnosticsEngine::new();
        let diags = engine.diagnose("fn main() -> i64 { return 0; }");
        assert!(
            diags.is_empty(),
            "valid source should produce no diagnostics"
        );
    }

    #[test]
    fn lex_error_produces_diagnostic_with_span() {
        let engine = DiagnosticsEngine::new();
        let diags = engine.diagnose("fn main() -> i64 { return $; }");
        assert_eq!(diags.len(), 1);
        assert!(matches!(diags[0].kind, EngineDiagnosticKind::LexError(_)));
        // Span should point to the problematic character
        assert!(
            diags[0].span.start < diags[0].span.end || diags[0].span.start == diags[0].span.end
        );
    }

    #[test]
    fn parse_error_produces_diagnostic_with_span() {
        let engine = DiagnosticsEngine::new();
        let diags = engine.diagnose("fn main() -> i64 { return 1 + ; }");
        assert_eq!(diags.len(), 1);
        assert!(matches!(diags[0].kind, EngineDiagnosticKind::ParseError(_)));
    }

    #[test]
    fn type_check_error_produces_diagnostic_with_span() {
        let engine = DiagnosticsEngine::new();
        let diags = engine.diagnose("fn main() -> i64 { return undefined_var; }");
        assert_eq!(diags.len(), 1);
        assert!(matches!(
            diags[0].kind,
            EngineDiagnosticKind::TypeCheckError(_)
        ));
    }

    #[test]
    fn fail_fast_returns_at_most_one_diagnostic() {
        let engine = DiagnosticsEngine::new();
        // Source with lex error — only the first error fires
        let diags = engine.diagnose("$ undefined_var");
        assert_eq!(diags.len(), 1);
    }

    #[test]
    fn lex_error_json_contains_kind_and_span() {
        let engine = DiagnosticsEngine::new();
        let diags = engine.diagnose("fn main() -> i64 { return $; }");
        assert!(diags[0].error_json.contains("\"kind\""));
        assert!(diags[0].error_json.contains("\"start\""));
        assert!(diags[0].error_json.contains("\"end\""));
    }

    #[test]
    fn type_check_error_json_contains_message() {
        let engine = DiagnosticsEngine::new();
        let diags = engine.diagnose("fn main() -> i64 { return undefined_var; }");
        assert!(diags[0].error_json.contains("\"message\""));
    }

    #[test]
    fn empty_source_handled_gracefully() {
        let engine = DiagnosticsEngine::new();
        let diags = engine.diagnose("");
        // Empty source → parse error (EmptyProgram) or lex produces empty tokens
        // Either way, diagnose should not panic and should produce a diagnostic
        assert_eq!(diags.len(), 1);
    }
}
